#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3

LIBPATH=/usr/local/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="ERUS"

player="src/erus_player"
coach="src/erus_coach"

config_player="./src/player.conf"
config_formation="./src/formations.conf"
# config_dir="./config/formations-dt"
coach_config="./src/coach.conf"

# opt="--player-config ${config} --config_dir ${config_dir}"
# opt="--f ${config}"
# opt="${opt} -h ${HOST} -t ${teamname}"

opt="-num ${NUM} -host ${HOST} -team ${teamname} -f ${config_formation} -c ${config_player}"

# coachopt="--coach-config ${coach_config}"
# coachopt="${coachopt} -h ${HOST} -t ${teamname}"

coachopt="-host ${HOST} -team ${teamname} -f ${config_formation}"

# team_graphic="--use_team_graphic on --team_graphic_file ./team_logo.xpm"
# coachopt="${coachopt} ${team_graphic}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt
        ;;
    2)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
